# Generated by Django 5.2.7 on 2025-11-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
    ]
