# Generated by Django 5.2.7 on 2025-11-08 10:25
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_trigram_extt'),
    ]

    operations = [
        TrigramExtension(),
    ]
